### ISSUE TITLE
Make Dockerfile/entrypoint build assets

### ISSUE THREAD

**Issue by namedgraph** [Ontotext-AD/graphdb-workbench#1718]
Hi,

If I see `docker-compose.yml` in a project, I expect that `docker-compose up` or `docker-compose up --build` will bring it up for me.
This was not the case here, because it could not find the `dist` folder, which turned out I had to build locally.

The Dockerfile/entrypoint should be able to build all the required assets within the container (e.g. `RUN npm run build`), instead of having to do it locally. Is there are reason why it's not setup like that? Consider this a feature request :)

**Comment by namedgraph** [comment]
I think I completed the pre-requisite steps and ran `docker-compose up --build` but there is nothing on http://localhost:7200 :/

**Comment by namedgraph** [comment]
I built the `dist` folder and then ran `docker-compose up --build` but there's no server on http://localhost :/

**Comment by svilenvelikov** [comment]
@namedgraph This docker-compose is used to run the acceptance tests on CI and not to start and use the application locally.

**Comment by namedgraph** [comment]
@svilenvelikov thanks. Well then two things:
* that is not obvious from the README
* can you please provide a `docker-compose.yml` that simply brings up the Workbench+GraphDB (and builds the necessary artifacts)? Because obviously this can be done. The test-running file can extend it (as `docker-compose.test.yml` or smth)

**Comment by svilenvelikov** [comment]
@namedgraph This setup in the docker-compose assumes that you for some reason want to run the workbench as a separate application. This usually is not needed, because if you just download and run GraphDB instance, you'll have access to the builtin workbench. In other words, the only reason for someone to run the workbench as standalone application would be if he/she wants to do do some testing with a customized application. For example, during development, we start a GraphDB instance either from the source code or from some distribution (executable, docker image, etc.) and run the workbench with `npm start` for which we previously did `npm install` to get the needed dependencies.

**Comment by namedgraph** [comment]
@svilenvelikov thanks for the clarification. I was simply looking for `docker-compose.yml` for GraphDB and found one in this repo. Can you point me to a better one?
There was apparently one here but now it's gone? https://github.com/Ontotext-AD/graphdb-docker/blob/master/docker-compose.yml

**Comment by namedgraph** [comment]
OK it looks it's as simple as this
```yaml
services:
  graphdb:
    image: ontotext/graphdb:10.8.0
    ports:
      - 7200:7200
    volumes:
      - ./data:/opt/graphdb/home
      - ./imports:/root/graphdb-import
```
Would just be nice to have it provided as part of https://github.com/Ontotext-AD/graphdb-docker/.
